#!/usr/bin/env bash
# Kopiert domain.Canonicalize + diacriticFold VERBATIM aus dem Service-Modul
# in die Probe. Notwendig, weil Gos internal/-Regel pfadbasiert ist: das
# poc/-Modul (github.com/jobrunner/hostus-poc) darf
# github.com/jobrunner/hostus/internal/domain auch mit `replace` nicht
# importieren. Statt die Kanonisierung nachzubauen (und damit womoeglich
# anders zu messen als der Dienst) wird sie hier zeilengenau extrahiert;
# `--check` verifiziert, dass die Kopie noch identisch ist.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SRC="$ROOT/internal/domain/taxon.go"
DST="$ROOT/poc/measure/bridge/canonicalize.go"

extract() {
  awk '/^\/\/ Canonicalize normalizes a scientific name/,/^}$/' "$SRC"
  echo
  awk '/^\/\/ diacriticFold maps common Latin letters/,/^}$/' "$SRC"
}

tmp="$(mktemp)"
{
  echo "package main"
  echo
  echo 'import "strings"'
  echo
  echo "// Code generated by poc/measure/gen_canonicalize.sh from"
  echo "// internal/domain/taxon.go. DO NOT EDIT."
  echo
  extract
} > "$tmp"

if [[ "${1:-}" == "--check" ]]; then
  diff -u "$DST" "$tmp" && echo "canonicalize.go is in sync with internal/domain/taxon.go"
else
  mv "$tmp" "$DST"
  echo "wrote $DST"
fi
