#!/usr/bin/env bash
# Kopiert internal/domain/normalize.go VERBATIM (nur die package-Zeile wird
# ersetzt) in die Mess-Probe. Gleicher Grund wie gen_canonicalize.sh: Gos
# internal/-Regel ist pfadbasiert, das poc/-Modul darf
# github.com/jobrunner/hostus/internal/domain nicht importieren. Die
# Normalisierungsregeln nachzubauen hiesse, etwas anderes zu messen als der
# Dienst tut; `--check` verifiziert, dass die Kopie identisch ist.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SRC="$ROOT/internal/domain/normalize.go"
DST="$ROOT/poc/measure/bridge/normalize.go"

tmp="$(mktemp)"
{
  echo "// Code generated by poc/measure/gen_normalize.sh from"
  echo "// internal/domain/normalize.go. DO NOT EDIT."
  echo
  sed 's/^package domain$/package main/' "$SRC"
} > "$tmp"

if [[ "${1:-}" == "--check" ]]; then
  diff -u "$DST" "$tmp" && echo "normalize.go is in sync with internal/domain/normalize.go"
else
  mv "$tmp" "$DST"
  echo "wrote $DST"
fi
