#!/usr/bin/env bash
# Kopiert die Kanonisierung und die Similarity-Metrik VERBATIM aus dem
# Service-Modul in die fuzzyrecall-Probe. Notwendig aus demselben Grund wie
# bei gen_canonicalize.sh: Gos internal/-Regel ist pfadbasiert, das poc/-Modul
# darf internal/domain auch mit `replace` nicht importieren. Nachbauen waere
# schlimmer als kopieren — dann messen wir eine andere Metrik als der Dienst.
# `--check` verifiziert, dass die Kopie noch identisch ist.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DST="$ROOT/poc/measure/fuzzyrecall/domain.go"

extract() {
  awk '/^\/\/ Canonicalize normalizes a scientific name/,/^}$/' "$ROOT/internal/domain/taxon.go"
  echo
  awk '/^\/\/ diacriticFold maps common Latin letters/,/^}$/' "$ROOT/internal/domain/taxon.go"
  echo
  awk '/^\/\/ FuzzyThreshold/,/^const FuzzyThreshold/' "$ROOT/internal/domain/match.go"
  echo
  awk '/^\/\/ Similarity returns/,/^}$/' "$ROOT/internal/domain/match.go"
  echo
  awk '/^\/\/ levenshteinDistance computes/,/^}$/' "$ROOT/internal/domain/match.go"
}

tmp="$(mktemp)"
{
  echo "package main"
  echo
  echo 'import "strings"'
  echo
  echo "// Code generated by poc/measure/gen_fuzzy_domain.sh from"
  echo "// internal/domain/{taxon,match}.go. DO NOT EDIT."
  echo
  extract
} > "$tmp"

if [[ "${1:-}" == "--check" ]]; then
  diff -u "$DST" "$tmp" && echo "domain.go is in sync with internal/domain"
else
  mv "$tmp" "$DST"
  echo "wrote $DST"
fi
