package main

import "strings"

// Code generated by poc/measure/gen_fuzzy_domain.sh from
// internal/domain/{taxon,match}.go. DO NOT EDIT.

// Canonicalize normalizes a scientific name (or name fragment) into a
// comparison key: it trims leading/trailing whitespace, collapses internal
// whitespace runs to a single space, lower-cases, and strips diacritics.
// This mirrors the SQLite FTS5 "unicode61 remove_diacritics 2" tokenizer so
// keys computed here line up with the ones the database computes at index
// time. It does NOT strip punctuation or hyphens, and it does NOT touch
// distinct letters/words — "otites" and "otitis" remain distinct.
func Canonicalize(name string) string {
	fields := strings.Fields(name)
	joined := strings.ToLower(strings.Join(fields, " "))

	var b strings.Builder
	b.Grow(len(joined))
	for _, r := range joined {
		if plain, ok := diacriticFold[r]; ok {
			b.WriteRune(plain)
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}

// diacriticFold maps common Latin letters carrying diacritics (as used in
// botanical author names and place names) to their base ASCII letter. This
// is a fixed table rather than a full Unicode-normalization dependency,
// keeping internal/domain free of third-party imports per CLAUDE.md's
// "Allowed Libraries Only" constraint. It covers the Latin-1 Supplement and
// the common Latin Extended-A range; it is not a complete Unicode
// decomposition.
//
// It deliberately EXCLUDES 'ß', 'ł', 'ø', 'đ': these are not base+combining-
// mark decompositions in Unicode (there is no plain "s"/"l"/"o"/"d" +
// diacritic to strip), so SQLite's FTS5 `unicode61 remove_diacritics 2`
// tokenizer — used to index fts_name (see adapters/sqlite/schema.sql) — does
// NOT fold them either (verified empirically; see
// internal/adapters/sqlite/fts_parity_test.go). Folding them here anyway
// would make Canonicalize's comparison keys diverge from the ones the FTS5
// index computes at query time, breaking exact-match lookups keyed by
// canonical name. Confirmed via the same probe: every OTHER letter in this
// table (a/e/i/u/y/n/c/z/r/t/g families and 'ď') does fold under unicode61
// remove_diacritics=2, matching this table's coverage.
var diacriticFold = map[rune]rune{
	'à': 'a', 'á': 'a', 'â': 'a', 'ã': 'a', 'ä': 'a', 'å': 'a', 'ā': 'a', 'ă': 'a', 'ą': 'a',
	'è': 'e', 'é': 'e', 'ê': 'e', 'ë': 'e', 'ē': 'e', 'ĕ': 'e', 'ė': 'e', 'ę': 'e', 'ě': 'e',
	'ì': 'i', 'í': 'i', 'î': 'i', 'ï': 'i', 'ĩ': 'i', 'ī': 'i', 'ĭ': 'i', 'į': 'i',
	'ò': 'o', 'ó': 'o', 'ô': 'o', 'õ': 'o', 'ö': 'o', 'ō': 'o', 'ŏ': 'o', 'ő': 'o',
	'ù': 'u', 'ú': 'u', 'û': 'u', 'ü': 'u', 'ũ': 'u', 'ū': 'u', 'ŭ': 'u', 'ů': 'u', 'ű': 'u', 'ų': 'u',
	'ý': 'y', 'ÿ': 'y',
	'ñ': 'n', 'ń': 'n', 'ņ': 'n', 'ň': 'n',
	'ç': 'c', 'ć': 'c', 'ĉ': 'c', 'ċ': 'c', 'č': 'c',
	'ś': 's', 'ŝ': 's', 'ş': 's', 'š': 's',
	'ź': 'z', 'ż': 'z', 'ž': 'z',
	'ĺ': 'l', 'ļ': 'l', 'ľ': 'l',
	'ř': 'r', 'ŕ': 'r', 'ŗ': 'r',
	'ď': 'd',
	'ť': 't', 'ţ': 't',
	'ğ': 'g', 'ģ': 'g',
}

// FuzzyThreshold is the minimum Similarity score for a fuzzy candidate to be
// considered plausible enough to surface as a MatchFuzzy result (always
// with RequiresReview, per spec §B.2) rather than left UNRESOLVABLE.
//
// Tuned against the two reference cases spec §B.2 names explicitly: a
// single-letter epithet typo across otherwise-identical names ("silene
// otitis" vs the correctly-spelled "silene otites") scores ~0.923 and must
// match; two genuinely different congeneric species ("festuca ovina" vs
// "festuca rubra", sharing only the genus and word count) score ~0.692 and
// must not. 0.85 sits strictly between the two with headroom on both sides.
const FuzzyThreshold = 0.85

// Similarity returns a's and b's normalized Levenshtein similarity, in
// [0,1]: 1 - distance/maxLen, where distance is the Levenshtein edit
// distance (in runes) and maxLen is the longer input's rune length. 1.0
// means identical. a and b are expected to already be canonicalized by the
// caller (e.g. via Canonicalize) — Similarity does no normalization of its
// own and is symmetric: Similarity(a, b) == Similarity(b, a).
//
// Both inputs empty -> 1.0 (zero edits needed to turn "" into ""); exactly
// one empty -> 0.0 (every rune of the non-empty side would need inserting,
// i.e. distance == maxLen).
func Similarity(a, b string) float64 {
	ra, rb := []rune(a), []rune(b)
	if len(ra) == 0 && len(rb) == 0 {
		return 1.0
	}
	if len(ra) == 0 || len(rb) == 0 {
		return 0.0
	}
	maxLen := len(ra)
	// len(rb) > maxLen is a genuinely equivalent mutant at
	// CONDITIONALS_BOUNDARY (>=): when len(rb) == maxLen exactly, the
	// reassignment below sets maxLen to the value it already holds, so no
	// test can observe a difference at that boundary (same reasoning as
	// the documented equivalents in internal/application/suggest.go).
	if len(rb) > maxLen {
		maxLen = len(rb)
	}
	return 1.0 - float64(levenshteinDistance(ra, rb))/float64(maxLen)
}

// levenshteinDistance computes the classic Levenshtein edit distance (in
// runes) between a and b via the standard O(len(a)*len(b))-time,
// O(min(len(a),len(b)))-space dynamic-programming table: two rolling rows
// instead of a full matrix, since only the previous row is ever needed.
func levenshteinDistance(a, b []rune) int {
	// Iterate over the shorter side so the rolling rows stay as small as
	// possible. len(a) > len(b), at CONDITIONALS_BOUNDARY (>=) AND
	// CONDITIONALS_NEGATION (<), are both genuinely equivalent mutants
	// here: the swap only ever changes which slice is labeled "a" vs "b"
	// for the DP table's internal bookkeeping (row size, iteration order)
	// — Levenshtein distance is symmetric in its two inputs regardless of
	// that labeling, so the computed distance is identical whichever way
	// (or whether) the swap fires, at every input length, not just at the
	// len(a)==len(b) boundary. Only performance (rolling-row width)
	// depends on it, which no correctness-observing test can assert on.
	if len(a) > len(b) {
		a, b = b, a
	}
	prev := make([]int, len(a)+1)
	curr := make([]int, len(a)+1)
	for i := range prev {
		prev[i] = i
	}
	for j := 1; j <= len(b); j++ {
		curr[0] = j
		for i := 1; i <= len(a); i++ {
			cost := 1
			if a[i-1] == b[j-1] {
				cost = 0
			}
			deletion := prev[i] + 1
			insertion := curr[i-1] + 1
			substitution := prev[i-1] + cost
			m := deletion
			// insertion < m and substitution < m are each a genuinely
			// equivalent mutant at CONDITIONALS_BOUNDARY (<=): when the
			// right-hand value ties the current m exactly, reassigning m
			// to it is a no-op (same value), so no test can observe a
			// difference at that tie — the classic min-selection idiom's
			// boundary case (same reasoning as the documented equivalents
			// in internal/application/suggest.go). CONDITIONALS_NEGATION
			// (>=) on either line is NOT equivalent, though: it flips which
			// values trigger reassignment far more broadly (any
			// insertion/substitution not strictly less, not just those
			// tied at the boundary), which is a real, observable
			// mis-computation — see TestSimilarity's unequal-length cases.
			if insertion < m {
				m = insertion
			}
			if substitution < m {
				m = substitution
			}
			curr[i] = m
		}
		prev, curr = curr, prev
	}
	return prev[len(a)]
}
