package main

import "strings"

// Code generated by poc/measure/gen_canonicalize.sh from
// internal/domain/taxon.go. DO NOT EDIT.

// Canonicalize normalizes a scientific name (or name fragment) into a
// comparison key: it trims leading/trailing whitespace, collapses internal
// whitespace runs to a single space, lower-cases, and strips diacritics.
// This mirrors the SQLite FTS5 "unicode61 remove_diacritics 2" tokenizer so
// keys computed here line up with the ones the database computes at index
// time. It does NOT strip punctuation or hyphens, and it does NOT touch
// distinct letters/words — "otites" and "otitis" remain distinct.
func Canonicalize(name string) string {
	fields := strings.Fields(name)
	joined := strings.ToLower(strings.Join(fields, " "))

	var b strings.Builder
	b.Grow(len(joined))
	for _, r := range joined {
		if plain, ok := diacriticFold[r]; ok {
			b.WriteRune(plain)
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}

// diacriticFold maps common Latin letters carrying diacritics (as used in
// botanical author names and place names) to their base ASCII letter. This
// is a fixed table rather than a full Unicode-normalization dependency,
// keeping internal/domain free of third-party imports per CLAUDE.md's
// "Allowed Libraries Only" constraint. It covers the Latin-1 Supplement and
// the common Latin Extended-A range; it is not a complete Unicode
// decomposition.
//
// It deliberately EXCLUDES 'ß', 'ł', 'ø', 'đ': these are not base+combining-
// mark decompositions in Unicode (there is no plain "s"/"l"/"o"/"d" +
// diacritic to strip), so SQLite's FTS5 `unicode61 remove_diacritics 2`
// tokenizer — used to index fts_name (see adapters/sqlite/schema.sql) — does
// NOT fold them either (verified empirically; see
// internal/adapters/sqlite/fts_parity_test.go). Folding them here anyway
// would make Canonicalize's comparison keys diverge from the ones the FTS5
// index computes at query time, breaking exact-match lookups keyed by
// canonical name. Confirmed via the same probe: every OTHER letter in this
// table (a/e/i/u/y/n/c/z/r/t/g families and 'ď') does fold under unicode61
// remove_diacritics=2, matching this table's coverage.
var diacriticFold = map[rune]rune{
	'à': 'a', 'á': 'a', 'â': 'a', 'ã': 'a', 'ä': 'a', 'å': 'a', 'ā': 'a', 'ă': 'a', 'ą': 'a',
	'è': 'e', 'é': 'e', 'ê': 'e', 'ë': 'e', 'ē': 'e', 'ĕ': 'e', 'ė': 'e', 'ę': 'e', 'ě': 'e',
	'ì': 'i', 'í': 'i', 'î': 'i', 'ï': 'i', 'ĩ': 'i', 'ī': 'i', 'ĭ': 'i', 'į': 'i',
	'ò': 'o', 'ó': 'o', 'ô': 'o', 'õ': 'o', 'ö': 'o', 'ō': 'o', 'ŏ': 'o', 'ő': 'o',
	'ù': 'u', 'ú': 'u', 'û': 'u', 'ü': 'u', 'ũ': 'u', 'ū': 'u', 'ŭ': 'u', 'ů': 'u', 'ű': 'u', 'ų': 'u',
	'ý': 'y', 'ÿ': 'y',
	'ñ': 'n', 'ń': 'n', 'ņ': 'n', 'ň': 'n',
	'ç': 'c', 'ć': 'c', 'ĉ': 'c', 'ċ': 'c', 'č': 'c',
	'ś': 's', 'ŝ': 's', 'ş': 's', 'š': 's',
	'ź': 'z', 'ż': 'z', 'ž': 'z',
	'ĺ': 'l', 'ļ': 'l', 'ľ': 'l',
	'ř': 'r', 'ŕ': 'r', 'ŗ': 'r',
	'ď': 'd',
	'ť': 't', 'ţ': 't',
	'ğ': 'g', 'ģ': 'g',
}
